version: "3.9"
services:
  taskapi:
    ports:
      - 80
    environment:
      - FLASK_RUN_PORT=80
    build:
      context: ./py/taskapi/
      dockerfile: Dockerfile
  taskapiclient:
    environment:
      - TASK_API_BASE_URL=http://taskapi:80
      - APPLICATIONINSIGHTS_KEY=ad44edfb-6056-4efc-ba29-fa17fea1b422
      - LOG_LEVEL=DEBUG
    depends_on:
      - taskapi
    build:
      context: ./py/taskapiclient/
      dockerfile: Dockerfile
