version: "3.9"
services:
  authapi:
    ports:
      - 80
    environment:
      - FLASK_RUN_PORT=80
      - LOG_LEVEL=DEBUG
    build:
      context: ./py/authapi/
      dockerfile: Dockerfile
  taskapi:
    ports:
      - 80
    environment:
      - FLASK_RUN_PORT=80
    depends_on:
      - authapi
    build:
      context: ./py/taskapi/
      dockerfile: Dockerfile
  taskapiclient:
    environment:
      - TASK_API_BASE_URL=http://taskapi:80
      - APPLICATIONINSIGHTS_KEY=ad44edfb-6056-4efc-ba29-fa17fea1b422
      - LOG_LEVEL=DEBUG
      - AUTH_API_BASE_URL=http://authapi:80
      - CLIENT_ID="badapp"
      - SECRET="foobar"
    depends_on:
      - taskapi
    build:
      context: ./py/taskapiclient/
      dockerfile: Dockerfile
