version: "3.9"
services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd!
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=passw0rd!
  authapi:
    ports:
      - 80
    environment:
      - FLASK_RUN_PORT=80
      - LOG_LEVEL=DEBUG
    build:
      context: ./py/authapi/
      dockerfile: Dockerfile
  taskapi:
    ports:
      - 80
    environment:
      - FLASK_RUN_PORT=80
    depends_on:
      - authapi
      - db
    build:
      context: ./py/taskapi/
      dockerfile: Dockerfile
  taskapiclient:
    environment:
      - TASK_API_BASE_URL=http://taskapi:80
      - APPLICATIONINSIGHTS_KEY=499e479a-5879-4c70-96e4-bbb2df9fc32b
      - LOG_LEVEL=DEBUG
      - AUTH_API_BASE_URL=http://authapi:80
      - CLIENT_ID="taskapiclient"
      - SECRET="foobar"
      - RUN_INTERVAL=2
    depends_on:
      - taskapi
    build:
      context: ./py/taskapiclient/
      dockerfile: Dockerfile
